const productsData = [ {
    id: 1,
    name: "iPhone X",
    category: "IphoneX",
    storage: "128 GB",
    img: "./img/iphonexB.jpg",
  },
    {
      id: 2,
      name: "iPhone XS",
      category: "IphoneX",
      storage: "128 GB",
      img: "./img/iphonexsB.jpg",
    }, {
      id: 3,
      name: "iPhone XS Max",
      category: "IphoneX",
      storage: "128 GB",
      img: "./img/iphonexsN.jpg",
    },
    {
      id: 4,
      name: "iPhone XR",
      category: "IphoneX",
      storage: "128 GB",
      img: "./img/iphonexrC.jpg",
    },
    {
      id: 5,
      name: "iPhone 11",
      category: "Iphone11",
      storage: "128 GB",
      img: "./img/iphone11V.jpg",
    },
    {
      id: 6,
      name: "iPhone 11 Pro",
      category: "Iphone11",
      storage: "128 GB",
      img: "./img/iphone11ProB.jpg",
    },
    {
      id: 7,
      name: "iPhone 11 Pro Max",
      category: "Iphone11",
      storage: "128 GB",
      img: "./img/iphone11ProMaxG.jpg",
    },
    {
      id: 8,
      name: "iPhone 12 mini",
      category: "Iphone12",
      storage: "64 GB",
      img: "./img/iphone12MiniR.jpg",
    },
    {
      id: 9,
      name: "iPhone 12",
      category: "Iphone12",
      storage: "64 GB",
      img: "./img/iphone12R.jpg",
    }, {
      id: 10,
      name: "iPhone 12 Pro",
      category: "Iphone12",
      storage: "64 GB",
      img: "./img/iphone12ProA.jpg",
    }, {
      id: 11,
      name: "iPhone 12 Pro Max",
      category: "Iphone12",
      storage: "64 GB",
      img: "./img/iphone12ProMaxG.jpg",
    },{
      id: 12,
      name: "iPhone 13 Mini",
      category: "Iphone13",
      storage: "256 GB",
      img: "./img/iphone13MiniA.jpg",
    },
    {
      id: 13,
      name: "iPhone 13",
      category: "Iphone13",
      storage: "256 GB",
      img: "./img/iphone13A.jpg",
    },{
      id: 14,
      name: "iPhone 13 Pro",
      category: "Iphone13",
      storage: "256 GB",
      img: "./img/iphone13ProB.jpg",
    },
    {
      id: 15,
      name: "iPhone 13 Pro Max",
      category: "Iphone13",
      storage: "256 GB",
      img: "./img/iphone13ProMaxA.jpg",
    },
    {
      id: 16,
      name: "iPhone 14",
      category: "Iphone14",
      storage: "128 GB",
      img: "./img/iphone14B.jpg",
    },
    {
      id: 17,
      name: "iPhone 14 Plus",
      category: "Iphone14",
      storage: "128 GB",
      img: "./img/iphone14PlusB.jpg",
    },  {
      id: 18,
      name: "iPhone 14 Pro",
      category: "Iphone14",
      storage: "128 GB",
      img: "./img/iphone14ProM.jpg",
    },  {
      id: 19,
      name: "iPhone 14 Pro Max",
      category: "Iphone14",
      storage: "128 GB",
      img: "./img/iphone14ProMaxN.jpg",
    },
    {
      id: 20,
      name: "iPhone 15",
      category: "Iphone15",
      storage: "512 GB",
      img: "./img/iphone15N.jpg",
    },  {
      id: 21,
      name: "iPhone 15 Plus",
      category: "Iphone15",
      storage: "128 GB",
      img: "./img/iphone15PlusB.jpg",
    },  {
      id: 22,
      name: "iPhone 15 Pro",
      category: "Iphone15",
      storage: "128 GB",
      img: "./img/iphone15ProN.jpg",
    },  {
      id: 23,
      name: "iPhone 15 Pro Max",
      category: "Iphone15",
      storage: "128 GB",
      img: "./img/iphone15ProMaxB.jpg",
    }, {
      id: 23,
      name: "Mp5 Gel",
      category: "Juguetes",
      storage: "hidrogel",
      img: "./img/gelmp5.jpg",
    },
];

export default productsData;